import * as fs from 'node:fs';
import * as path from 'node:path';
import type { RiskClassification, ScanResult } from './types.js';

export interface GenerateAnnexIvOptions {
  outputDir: string;
  systemName: string;
  provider: string;
  description?: string;
  language?: string;
}

function mdEscape(s: string): string {
  return s.replace(/\|/g, '\\|');
}

export function generateAnnexIvDocs(
  scan: ScanResult,
  risk: RiskClassification,
  opts: GenerateAnnexIvOptions,
): { files: string[] } {
  const out = path.resolve(opts.outputDir);
  fs.mkdirSync(out, { recursive: true });

  const lang = opts.language ?? 'en';
  const files: string[] = [];

  const technical = `---
title: Technical Documentation (Annex IV style outline)
language: ${lang}
generated_by: "@asterpay/attest-sdk"
---

# Technical documentation — ${mdEscape(opts.systemName)}

> **Disclaimer:** This is a developer-generated scaffold to support EU AI Act documentation work. It is **not** legal advice and does not replace conformity assessment or counsel.

## 1. General description

| Field | Value |
|-------|-------|
| System name | ${mdEscape(opts.systemName)} |
| Provider / deployer | ${mdEscape(opts.provider)} |
| Description | ${mdEscape(opts.description ?? '—')} |
| Scanned root | \`${mdEscape(scan.rootDir)}\` |
| Files scanned | ${scan.filesScanned} |

## 2. Intended purpose

Describe the intended purpose, end-users, and context of deployment. (Fill manually.)

## 3. AI components detected (automated scan)

The following third-party AI-related packages were detected from import analysis:

${scan.packagesDetected.length ? scan.packagesDetected.map((p) => `- \`${mdEscape(p)}\``).join('\n') : '_None detected — verify REST/SDK usage not covered by static scan._'}

### Findings detail

| Package | File | Line | Kind |
|---------|------|------|------|
${scan.findings.length ? scan.findings.map((f) => `| ${mdEscape(f.packageName)} | ${mdEscape(f.filePath)} | ${f.line} | ${f.kind} |`).join('\n') : '| — | — | — | — |'}

## 4. Risk classification (heuristic)

| Field | Value |
|-------|-------|
| Level | **${risk.level}** |
| Rationale | ${mdEscape(risk.reason)} |
| Relevant articles (indicative) | ${risk.articles.join(', ') || '—'} |

### Warnings

${risk.warnings.length ? risk.warnings.map((w) => `- ${mdEscape(w)}`).join('\n') : '_None_'}

## 5. Data governance (Article 10) — template

- Training data: _N/A / describe_
- Input data: _describe categories, retention, minimisation_
- Data quality measures: _describe_

## 6. Record-keeping & logging (Article 12) — template

- Log fields: model, purpose, timestamps, human oversight flags, PII flags.
- Retention policy: _define_
- Tamper-evidence: use \`@asterpay/attest-sdk\` audit log hash chain where applicable.

## 7. Transparency (Article 13 / limited-risk) — template

- User-facing disclosures: _link to UI copy_
- Machine-readable metadata: _optional_

## 8. Human oversight (Article 14) — template

- Override mechanisms: _describe_
- Human review workflows: _describe_

## 9. Accuracy, robustness, cybersecurity (Article 15) — template

- Testing strategy: _describe_
- Monitoring: _describe_
- Incident process: _describe_

## 10. Conformity & registration

- Conformity assessment route: _self / third-party_
- EU database registration: _status / ID_

---

_Generated by Attest — Powered by AsterPay._
`;

  const riskMd = `---
title: Risk assessment (working draft)
---

# Risk assessment — ${mdEscape(opts.systemName)}

## Summary

- **Heuristic risk level:** ${risk.level}
- **Reason:** ${mdEscape(risk.reason)}

## Risk management system (Article 9)

Document identification, analysis, evaluation, and mitigation of risks throughout the lifecycle. (Fill manually.)

## Post-market monitoring

Describe monitoring, feedback loops, and update policy. (Fill manually.)
`;

  const decl = `---
title: EU Declaration of Conformity (template)
---

# EU Declaration of Conformity — template

> Complete with legal review. This file is a non-binding placeholder.

1. AI system name: **${mdEscape(opts.systemName)}**
2. Provider: **${mdEscape(opts.provider)}**
3. The AI system complies with the requirements of Regulation (EU) 2024/1689 (EU AI Act) for the indicated risk class.
4. References to harmonised standards / specifications: _fill_
5. Notified body (if applicable): _fill_
6. Place, date, signature.

---

_Attest scaffold — not a signed legal document._
`;

  const p1 = path.join(out, 'technical-documentation.md');
  const p2 = path.join(out, 'risk-assessment.md');
  const p3 = path.join(out, 'conformity-declaration.md');
  fs.writeFileSync(p1, technical, 'utf8');
  fs.writeFileSync(p2, riskMd, 'utf8');
  fs.writeFileSync(p3, decl, 'utf8');
  files.push(p1, p2, p3);

  return { files };
}
